apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free-lunch.fullname" . }}-mongodb
  labels:
    {{- include "free-lunch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "free-lunch.name" . }}-mongodb
  template:
    metadata:
      labels:
        app: {{ include "free-lunch.name" . }}-mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.images.mongodb.repository }}:{{ .Values.images.mongodb.tag }}"
        imagePullPolicy: {{ .Values.images.mongodb.pullPolicy }}
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
          claimName: mongo-pvc
