apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "free-luch.fullname" . }}
  labels:
    {{- include "free-luch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "free-luch.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "free-luch.name" . }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 3
            periodSeconds: 3
