apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort  # Change this to LoadBalancer if you're using a cloud provider
  ports:
    - port: {{ .Values.nginx.port }}
      targetPort: {{ .Values.nginx.port }}
      nodePort: 30080  # Optional, if you want to expose a specific port
  selector:
    app: nginx
