apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  labels:
    role: prometheus-rulefiles
data:
  prometheus.rules: |
    groups:
    - name: cpu-usage
      rules:
      - alert: HighCPUUsage
        expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (pod) > 0.9
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High CPU usage detected"
          description: "The CPU usage is above 90% for more than 1 minute."
    - name: memory-usage
      rules:
      - alert: HighMemoryUsage
        expr: sum(container_memory_usage_bytes) by (pod) > 500000000
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High Memory usage detected"
          description: "The Memory usage is above 500MB for more than 1 minute."
    - name: http-requests
      rules:
      - alert: HighHTTPRequestRate
        expr: sum(rate(http_requests_total[1m])) by (service) > 100
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High HTTP request rate detected"
          description: "The HTTP request rate is above 100 requests per second for more than 1 minute."
