apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - name: amqp
      port: {{ (index .Values.rabbitmq.ports 0) }}
    - name: management
      port: {{ (index .Values.rabbitmq.ports 1) }}
  selector:
    app: rabbitmq
