{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "free-luch.serviceAccountName" . }}
  labels:
    {{- include "free-luch.labels" . | nindent 4 }}
{{- end }}
